### ISSUE TITLE
Container image not overwritten on later deployments

### ISSUE THREAD

**Issue by korridor** [scaleway/serverless-scaleway-functions#111]
Steps to reproduce:
 - Deploy a container with the serverless framework
 - Change the image and tag manually in Scaleway Console
 - Redeploy with the serverless framework

I would have assumed the redeployment would overwrite the manually set image and tag, but it just seems to ignore the image/tag setting.

**Comment by thomas-tacquet** [comment]
Hello 👋 
Thank you for the report and the reproduce steps, I opened a PR to fix that so I close this issue.
