### ISSUE TITLE
Define images instead of building them

### ISSUE THREAD

**Issue by boredland** [scaleway/serverless-scaleway-functions#114]
Hi there! As we have a somewhat special build-process for our images, I would prefer a solution, where I can pass an image name when deploying containers, instead of building them via the serverless yaml. Do you think that would be feasible?

**Comment by thomas-tacquet** [comment]
Hello 👋 Yes it's a nice to have feature, do you want to be able to use only images from Scaleway's Container Registry or you want to use external images from public registries ? 🤔

**Comment by boredland** [comment]
While both would certainly be interesting, priority for us would be inside scw registry

**Comment by thomas-tacquet** [comment]
This item is a part of our roadmap, thank you for the feature suggestion, for updates of new features do not hesitate to follow us on Slack 👌

I close the isssue (without locking conversation) for now as it will be added in the future.

**Comment by till1993** [comment]
@thomas-tacquet Hey :) 

we also need this feature and were wondering if there is a timeline for it?
Our use case within a pipeline is:

- run tests
- build image and get a tag
- deploy image to staging environment
- deploy image to production environment

Without this feature, we build an image for each environment, which is actually bad practice.

Best regards.
