### ISSUE TITLE
Trigger schedule check is too strict

### ISSUE THREAD

**Issue by tdelmas** [scaleway/serverless-scaleway-functions#128]
When creating a trigger with `schedule`, that test:

https://github.com/scaleway/serverless-scaleway-functions/blob/master/shared/validate.js#L27-L34

Refuses the syntax [`1-59/15 * * * *`](https://crontab.guru/#1-59/15_*_*_*_*) 

The UI in https://console.scaleway.com/ does accept it when creating a new trigger

**Comment by thomas-tacquet** [comment]
Merged 👌 

If you want to use the fix before the release you can clone this repository and `npm link` to it, example : 

`npm link ~/work/src/github.com/scaleway/serverless-scaleway-functions`
