### ISSUE TITLE
Scaleway Redis TLS cert and Promise-based programming

### ISSUE THREAD

**Issue by zdanl** [scaleway/serverless-scaleway-functions#131]
So, I've tried again with Redis last night. If you really care about the product, I would recommend & request the following: Provide at least one official Scaleway example for Redis Python3 and one for NodeJS using => Promises() on client.connectClient() and client.set(), but most importantly, display how to properly connect to a Remote Scalway Redis with which TLS parameters. Google is inconclusive on how to use the Certificate that you provide so smoothly.

If you want to rock it, and actually sell some of these things, provide an example of how to use it with Serverless functions AND Redis Persistence. Maybe offer Redis Enterprise. Redis, the Community version, so far, has to the best of my knowledge, two Persistence features, allowing to use it as a Primary Database rather than a Cache (which is great, Fields, .set/.get) and dynamic storage of Javascript type Objects, is much faster, and much comfortable, than dynamic or static creating of SQL statements.

I meanwhile set up a local address Redis, and that works smoothly, but I could still use an Example for how to use it with either TypeScript Express.JS properly or Python3 Flask.

**Comment by thomas-tacquet** [comment]
Hello 👋 

Yes this is a great idea 👌  we are working on a new separate repository dedicated to Serverless Functions and Containers examples : https://github.com/scaleway/serverless-examples 

Do not hesitate to contribute on our repositories to share your examples for the community, also I added your suggestions to our todo list

**Comment by cyclimse** [comment]
Thanks a lot for the suggestion 🙏

We've added a small example of a server less function that connects to a Redis store with TLS enabled: https://github.com/scaleway/serverless-examples/tree/main/functions/redis-tls

**Comment by zdanl** [comment]
Thanks!

________________________________

**Comment by zdanl** [comment]
Cool. Can you persist that with append-file and snapshots? Specific to weather fields, maybe? As in still thete after

service redis restart ?

________________________________

**Comment by zdanl** [comment]
You’re saying “Redis Store” in a way that makes me excited, but Search Engine returns just emphermal JSON Storage. Plz let me know if I’m missing something. Will submit an authenticated Redis example tonight, for (signed) session and encrypted user data read/write  From: Andy MérySent: Tuesday, 20 December 2022 14:31To: scaleway/serverless-scaleway-functionsCc: Dan Zulla; AuthorSubject: Re: [scaleway/serverless-scaleway-functions] Scaleway Redis TLS cert and Promise-based programming (Issue #131) Thanks a lot for the suggestion 🙏We've added a small example of a server less function that connects to a Redis store with TLS enabled: https://github.com/scaleway/serverless-examples/tree/main/functions/redis-tls—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
