### ISSUE TITLE
Add an example for Java

### ISSUE THREAD

**Issue by qlefevre** [scaleway/serverless-scaleway-functions#142]
I am a huge fan of Scaleway Serverless Functions.
 
I would like to contribute to examples provided in this plugin.
I have made a simple example written in Java in the spirit of the Flask project.

https://github.com/qlefevre/serverless-scaleway-containers

Can I do a pull-request ? Does the scaleway team have a special request ?

**Comment by thomas-tacquet** [comment]
👋  Awesome nice to read this 😁 

In this repository we try to keep simple example that focus on the Serverless Framework configuration, for more advanced examples like yours we are pleased to welcome your example in our repository dedicated to examples : https://github.com/scaleway/serverless-examples You can do a pull request in this repository 👌  

Thank you again to help the community by providing examples 😎

**Comment by qlefevre** [comment]
Thank you for your quick reply
I will make a pull request on this repo
