### ISSUE TITLE
typo : httpOption cannot be "disabled"

### ISSUE THREAD

**Issue by kdubuc** [scaleway/serverless-scaleway-functions#208]
Hi !

I think there is a typo in README 👍 

httpOption cannot be "disabled" because API doesn't let you do that : https://www.scaleway.com/en/developers/api/serverless-containers/

https://github.com/scaleway/serverless-scaleway-functions/blob/bb24dad1b0399438cabbd4bc9780207df9011e9a/README.md?plain=1#L153

**Comment by cyclimse** [comment]
Sorry for getting back to you after so much time has passed, but indeed this is a mistake, there's no such option available. Thanks a lot for reporting it!
