### ISSUE TITLE
Deprecation warning: SERVICE_OBJECT_NOTATION

### ISSUE THREAD

**Issue by untereiner** [scaleway/serverless-scaleway-functions#39]
> Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION

with 

>      
     Node Version:              14.4.0
     Framework Version:         2.39.1 (standalone)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1

**Comment by thomas-tacquet** [comment]
Thanks for raising an issue, this problem is solved, feel free to contact us if you have any other problem.
