### ISSUE TITLE
Deprecation warning: NEW_PACKAGE_PATTERNS

### ISSUE THREAD

**Issue by untereiner** [scaleway/serverless-scaleway-functions#41]
> Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS

with:

     Node Version:              14.4.0
     Framework Version:         2.39.1 (standalone)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1

**Comment by almottier** [comment]
Thanks, it is fixed in latest examples.
