### ISSUE TITLE
Allow `scwToken` to be declared out from the `serverless.yaml`

### ISSUE THREAD

**Issue by GerkinDev** [scaleway/serverless-scaleway-functions#76]
Hi,

I'm using the `serverless` framework along with this plugin to manage my FaaS. I'm also using the `scaleway-cli`.

I think the `serverless.yaml` file should be commited in my git repository, but I won't commit a secret token.

I've seen that page: https://www.serverless.com/framework/docs/providers/aws/cli-reference/config-credentials , but I don't know exactly what is supposed to be the key or the secret.

Would it be possible to load the secret key from another file, an env var, or even the scaleway-cli config ?

Cheers

**Comment by thomas-tacquet** [comment]
Hello,

I advise you to use environment variables since it's an easy way to manage an to keep out of unwanted `git commit` 😁 

You can use `SCW_SECRET_KEY` for your secret token and `SCW_DEFAULT_PROJECT_ID` for your project_id.

You can find out code that manage these variables here : https://github.com/scaleway/serverless-scaleway-functions/blob/master/provider/scalewayProvider.js#L49 

Let us know if the solution is ok for you.

**Comment by GerkinDev** [comment]
Great ! I didn't took the time to look at the source code, and the documentation isn't clear enough (or I just didn't found the info).

Could it be done by retrieving the scaleway CLI config ?

**Comment by GerkinDev** [comment]
Or even implement what is required to work with serverless built-in token storage https://www.serverless.com/framework/docs/providers/aws/cli-reference/config-credentials

**Comment by thomas-tacquet** [comment]
About de CLI config it's the same variable names, it should work but I haven't tried yet : https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/config.md 

For the built-in token management for serverless framework I'm going to look at 👌

**Comment by thomas-tacquet** [comment]
Thank you both for the questions/answers I'll update the documentation help future users 👌

**Comment by GerkinDev** [comment]
Yeah please. Recommending to put secrets in a config file that should AFAICT be committed in VCS seems super insecure, and IMO not even mentioned in a quickstart guide. Indeed, answers provide great workarounds.

**Comment by thomas-tacquet** [comment]
@GerkinDev @stackapaul  here is my PR : https://github.com/scaleway/serverless-scaleway-functions/pull/78 feel free to review it if I missed something 👍

**Comment by GerkinDev** [comment]
Great, thanks!
