### ISSUE TITLE
Support private functions and passing context in `serverless invoke`

### ISSUE THREAD

**Issue by korridor** [scaleway/serverless-scaleway-functions#97]
As far as I understand the code, the `serverless invoke` command is currently missing two important features.

1. It does not work with private functions/containers.
2. I can not pass any context with arguments like `--context`, `--data`, `--contextPath`, `--raw` and `--env` to the invoked function.

Are there any plans to add this in the near future?

**Comment by thomas-tacquet** [comment]
Hello 👋 

`serverless invoke`on private functions or containers is not available for the moment but we will implement it alongside missing arguments and options.

We aim to be fully compliant with the Serverless CLI spec : https://www.serverless.com/framework/docs/providers/aws/cli-reference/invoke 

Stay tuned for new releases 😄

**Comment by thomas-tacquet** [comment]
I close the issue as this is a part of our roadmap, thank you for requesting changes 👌
