### ISSUE TITLE
Serverless container based on private image can not be deployed

### ISSUE THREAD

**Issue by korridor** [scaleway/serverless-scaleway-functions#98]
I want to deploy a serverless container that uses a Dockerfile that is based on a image in the Scaleway Docker registry.

The image that I want to deploy looks something like this:

```dockerfile
FROM rg.nl-ams.scw.cloud/some/registry:tag

RUN something

COPY . .
```

This fails because the `build` command is not authenticated in the code, only the `push` command.

Code for build: https://github.com/scaleway/serverless-scaleway-functions/blob/master/deploy/lib/pushContainers.js#L40
Code for push: https://github.com/scaleway/serverless-scaleway-functions/blob/master/deploy/lib/pushContainers.js#L43

**Comment by norbjd** [comment]
Hello :wave: 

Thanks for reporting the issue. The linked PR should solve this. After the reviews are done, we'll release a new version with the fix!

**Comment by korridor** [comment]
Thanks, the pull request should work for my use case! 👍

**Comment by norbjd** [comment]
Hello @korridor, a new version (0.4.2) have been released and fixes this issue. Tell us if you are still facing this issue and we'll reopen it.
